### ISSUE TITLE
Decode 之後一問

### ISSUE THREAD

**Issue by xjimi** [ninefivefly/ObjMapper#2]
請問可否在所有屬性都賦值(decode完成)之後
修改其中幾個屬性的值

例如 api 只回傳了 buy 及 sell 2個屬性值：
    var buy: Double
    var sell: Double

    var customProfit
// customProfit 是多加入的屬性
// 必須在 buy 和 sell 都有值時才能相減
// customProfit = buy - sell
// 有想到在 get 裡運算
// 但若運算較為複雜 (ex: DateFormatter) 的處理
// 這樣效能會不太好，所以才想在所有屬性都賦值之後，再做一次的運算就好

**Comment by ninefivefly** [comment]
如果是OC的话，直接用延迟加载的特性来做就可以了。对于Swift，由于语言特性的限制，需要定义个存储属性和计算属性，见下面代码😁

`
    struct Store {

        var buy: Int
        var sell: Int
        private var _balance: Int
        var balance: Int {
            mutating get {
                ///判定是否初始化
                if _balance <= 0 {
                    ///复杂的运算
                    _balance = sell - buy;
                }
                return _balance;
            }
        }

    }

`

**Comment by xjimi** [comment]
了解了
謝謝您!
