### ISSUE TITLE
如果对象里面字段不合规(非普通类型)能转换么？后端PHP

### ISSUE THREAD

**Issue by HansRove** [ninefivefly/ObjMapper#3]
這庫很棒！~

// JSON:
{
    "uid":888888,
    "obj": {
         "test1": "xxxx",
         "test2": "xxxx"
      }
}

某天变成： 
// JSON:
{
    "uid":888888,
    "obj": []
}

obj不能使用@Backed var obj:  Model?    这种， 请问有什么更好的解决办法么？  PHP确实很蛋疼， 目前只能让该字段不返回， 但太多了最好能兼容一下，  望回复谢谢了！

**Comment by ninefivefly** [comment]
直接这样用 var obj: Model? ，model必须符合Codable协议就可以，不需要前面@Backed。

@Backed 是用在基础类型转换，比如在模型中的字段是int，但是json返回的是字符串，应用在这种场景的😊

**Comment by HansRove** [comment]
> 直接这样用 var obj: Model? ，model必须符合Codable协议就可以，不需要前面@Backed。
> 
> @Backed 是用在基础类型转换，比如在模型中的字段是int，但是json返回的是字符串，应用在这种场景的😊

这样会整个都转换不了，因为obj后端返回的是[] ,  数组和对象转不了  导致外模型整个转换都是错的

**Comment by ninefivefly** [comment]
可以这样写，用 JsonValue枚举类，可以把json全部转换成JsonValue枚举形式
`var obj: JsonValue?`  
如果obj是个数组，访问数组里面的内容用 obj.arrayValue，
如果obj是个整数，就用obj.intValue
